#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "YuanKeep"
email: 574583546@qq.com
description: "蔡汉源的个人博客"
keywords: "YuanKeep"

# 用户信息设置
weibo_username: caihanyuan
github_username: caihanyuan

# Markdown设置
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  auto_id_prefix: 'id-'
  syntax_highlighter: rouge
highlighter: rouge
highlight: true
encoding: "utf-8"


# 地址设置
baseurl: ""
url: "http://127.0.0.1:4000"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts" # 以前的 `post`， 在 Jekyll 2.2 里。
    values:
      layout: "post"
      author: YuanKeep


# duoshuo设置
# duoshuo_shortname: 

# 百度统计设置
# baidu_analysis:
